
name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "python-publish"
  cancel-in-progress: true

jobs:
  python-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build package
      run: scripts/build.py

    - name: Publish package
      if: ${{ false }}
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
